# hdmi drivers
obj-$(CONFIG_HDMI_IT6610_OLD)                             += it6610/
obj-$(CONFIG_HDMI_IT6610)                                 += it6610_shumb/
#obj-$(CONFIG_JZ4760_HDMI_DISPLAY)                              += ep932/
