# hdmi it6610 drivers
#obj-$(CONFIG_HDMI_IT6610)                             +=it6610_i2c.o  it6610_drv.o  chip_drv.o chip_sys.o i2c_fun.o
obj-$(CONFIG_HDMI_IT6610)                              +=it6610_drv.o  chip_drv.o chip_sys.o gpio_i2c.o jz_gpio_ctrl.o
