obj-$(CONFIG_VIVANTE_GPU_GC200)				+= VIVANTE_GAL2D_Unified_Src_drv_2010.2.5.3/
#obj-$(CONFIG_VIVANTE_GPU_GC860)			+= VIVANTE_GAL_Unified_Src_drv_2.5.3.2.2_for_ingenic/
#obj-$(CONFIG_VIVANTE_GPU_GC860)			+= VIVANTE_GAL_Unified_Src_drv_2.5.3.2.3.GPL/
#obj-$(CONFIG_VIVANTE_GPU_GC860)			+= VIVANTE_GAL_Unified_Src_drv_2.5.3.2.4.p5.noGPL/
#obj-$(CONFIG_VIVANTE_GPU_GC860)			+= VIVANTE_GAL_Unified_Src_drv_2.5.3.2.5.b7.noGPL/
obj-$(CONFIG_VIVANTE_GPU_GC860)				+= VIVANTE_GAL_Unified_Src_drv_2.5.3.2.5.p2.noGPL/
obj-$(CONFIG_LINUX_VIVANTE_GPU_GC860)			+= VIVANTE_GAL_Unified_Src_drv_2010.2.5/

